<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
      <PackageReference Include="MSTest.TestAdapter" Version="3.8.3" />
      <PackageReference Include="NAudio" Version="2.2.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="UI\resources\shoot-sound.wav" />
      <None Remove="UI\resources\WalkSound.wav" />
      <None Remove="UI\resources\HitSound.wav" />
      <None Remove="UI\resources\TakeShotSound.wav" />
      <EmbeddedResource Include="UI\resources\sounds\HitSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="UI\resources\sounds\ShootSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="UI\resources\sounds\TakeShotSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="UI\resources\sounds\WalkSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="UI\resources\images\StartMenuBackground.png" />
      <None Remove="UI\resources\images\icon.ico" />
      <EmbeddedResource Include="UI\resources\images\icon.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="UI\resources\fonts\DoomFont.ttf" />
      <None Remove="UI\resources\fonts\PixelizerFont.ttf" />
      <EmbeddedResource Include="UI\resources\fonts\PixelizerFont.ttf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="UI\resources\sounds\MenuSound.wav" />
      <EmbeddedResource Include="UI\resources\sounds\MenuSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="UI\forms\game\TraningForm\TraningForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\MainForm\MainForm.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UI\forms\" />
    </ItemGroup>

</Project>