<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
      <PackageReference Include="MSTest.TestAdapter" Version="3.8.3" />
      <PackageReference Include="NAudio" Version="2.2.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="UI\resources\shoot-sound.wav" />
      <EmbeddedResource Include="UI\resources\ShootSound.wav">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="UI\resources\WalkSound.wav" />
      <EmbeddedResource Include="UI\resources\WalkSound.wav">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="UI\resources\HitSound.wav" />
      <EmbeddedResource Include="UI\resources\HitSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="UI\resources\TakeShotSound.wav" />
      <EmbeddedResource Include="UI\resources\TakeShotSound.wav">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

</Project>